// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Play2GetherAPI.DAL;

namespace Play2GetherAPI.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20220604120149_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("Play2GetherAPI.Models.Activitie", b =>
                {
                    b.Property<long>("ActivitieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ActivitieId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Play2GetherAPI.Models.EmailToken", b =>
                {
                    b.Property<long>("EmailTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmailTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("EmailTokens");
                });

            modelBuilder.Entity("Play2GetherAPI.Models.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActivitieId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeDate")
                        .HasColumnType("Date");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Vacancies")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.HasIndex("ActivitieId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Play2GetherAPI.Models.Login", b =>
                {
                    b.Property<long>("LoginId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Play2GetherAPI.Models.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageId");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Play2GetherAPI.Models.Place", b =>
                {
                    b.Property<long>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<float>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<float>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("PlaceId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("Play2GetherAPI.Models.PlaceActivitie", b =>
                {
                    b.Property<long>("PlaceActivitieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActivitieId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaceActivitieId");

                    b.HasIndex("ActivitieId");

                    b.HasIndex("PlaceId");

                    b.ToTable("PlaceActivities");
                });

            modelBuilder.Entity("Play2GetherAPI.Models.PlaceProposition", b =>
                {
                    b.Property<long>("PlacePropositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Checked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<float>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<float>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("PlacePropositionId");

                    b.ToTable("PlacePropositions");
                });

            modelBuilder.Entity("Play2GetherAPI.Models.Premium", b =>
                {
                    b.Property<long>("PremiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Days")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PremiumId");

                    b.HasIndex("UserId");

                    b.ToTable("Premiums");
                });

            modelBuilder.Entity("Play2GetherAPI.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurName")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Play2GetherAPI.Models.UserEvent", b =>
                {
                    b.Property<long>("UserEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserEventId");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("Play2GetherAPI.Models.EmailToken", b =>
                {
                    b.HasOne("Play2GetherAPI.Models.User", "UserToken")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Play2GetherAPI.Models.Event", b =>
                {
                    b.HasOne("Play2GetherAPI.Models.Activitie", "ActivitieEvent")
                        .WithMany("Events")
                        .HasForeignKey("ActivitieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Play2GetherAPI.Models.Place", "Spot")
                        .WithMany("Events")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Play2GetherAPI.Models.User", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Play2GetherAPI.Models.Login", b =>
                {
                    b.HasOne("Play2GetherAPI.Models.User", "UserLogin")
                        .WithOne("Login")
                        .HasForeignKey("Play2GetherAPI.Models.Login", "LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Play2GetherAPI.Models.Message", b =>
                {
                    b.HasOne("Play2GetherAPI.Models.Event", "EventMessage")
                        .WithMany("Messages")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Play2GetherAPI.Models.User", "UserMessage")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Play2GetherAPI.Models.PlaceActivitie", b =>
                {
                    b.HasOne("Play2GetherAPI.Models.Place", "PlaceA")
                        .WithMany("PlaceActivities")
                        .HasForeignKey("ActivitieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Play2GetherAPI.Models.Activitie", "ActivitieP")
                        .WithMany("PlaceActivities")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Play2GetherAPI.Models.Premium", b =>
                {
                    b.HasOne("Play2GetherAPI.Models.User", "UserPremium")
                        .WithMany("Premiums")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Play2GetherAPI.Models.UserEvent", b =>
                {
                    b.HasOne("Play2GetherAPI.Models.Event", "EventU")
                        .WithMany("UsersEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Play2GetherAPI.Models.User", "UserE")
                        .WithMany("UserEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
